-- Prima nota (partita doppia) + regole per generare le scritture in automatico.
create table if not exists regole_scritture (
  id bigint generated by default as identity primary key,
  nome text not null,
  azienda text,
  origine text not null check (origine in ('fattura_acquisto','fattura_vendita','movimento_banca','movimento_carta')),
  banca text,
  numero_conto text,
  controparte_contiene text,
  descrizione_contiene text,
  descrizione_esclude text,
  tipo_documento text,
  verso text check (verso in ('dare','avere')),
  righe jsonb not null default '[]',   -- [{conto, lato:'dare'|'avere', importo:'totale'|'imponibile'|'iva'|'importo'}]
  priorita integer not null default 100,
  attiva boolean not null default true,
  automatica boolean not null default false,
  note text,
  volte_applicata integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists prima_nota (
  id uuid primary key default gen_random_uuid(),
  azienda text not null,
  data date not null,
  descrizione text,
  origine_tabella text,
  origine_id uuid,
  regola_id bigint references regole_scritture(id) on delete set null,
  stato text not null default 'bozza' check (stato in ('bozza','confermata')),
  created_at timestamptz not null default now(),
  unique (origine_tabella, origine_id)
);
create table if not exists prima_nota_righe (
  id uuid primary key default gen_random_uuid(),
  prima_nota_id uuid not null references prima_nota(id) on delete cascade,
  conto text not null,
  descrizione text,
  dare numeric not null default 0,
  avere numeric not null default 0
);
create index if not exists prima_nota_righe_pn on prima_nota_righe(prima_nota_id);
create index if not exists prima_nota_azienda_data on prima_nota(azienda, data);

-- una scrittura confermata deve quadrare
create or replace function prima_nota_controlla_quadratura() returns trigger language plpgsql as $$
declare d numeric; a numeric;
begin
  if new.stato = 'confermata' then
    select coalesce(sum(dare),0), coalesce(sum(avere),0) into d, a from prima_nota_righe where prima_nota_id = new.id;
    if round(d,2) <> round(a,2) or d = 0 then
      raise exception 'Scrittura non quadra: dare % avere %', d, a;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists prima_nota_quadratura on prima_nota;
create trigger prima_nota_quadratura before update of stato on prima_nota
  for each row execute function prima_nota_controlla_quadratura();

-- stesse policy permissive delle altre tabelle dell'app (accesso con chiave anon)
alter table regole_scritture enable row level security;
alter table prima_nota enable row level security;
alter table prima_nota_righe enable row level security;
create policy regole_scritture_all on regole_scritture for all using (true) with check (true);
create policy prima_nota_all on prima_nota for all using (true) with check (true);
create policy prima_nota_righe_all on prima_nota_righe for all using (true) with check (true);
